version : '3.7'
services:
  zabbix-pgsql:
    image: postgres:latest
    container_name: zabbix-postgres-db
    environment:
        POSTGRES_USER: zabbix
        POSTGRES_PASSWORD: <DB password goes here, make one up.>
        POSTGRES_DB: zabbix
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "zabbix-pgsql"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: <Password for DB you created at line 8>
    ports:
      - '10051:10051'
    links:
      - zabbix-pgsql
    depends_on:
      - zabbix-pgsql
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-pgsql
    environment:
      DB_SERVER_HOST: zabbix-pgsql
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: <Password for DB you created at line 8>
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: <Timezone goes here, e.g. Europe/Amsterdam>
    ports:
      - '80:8080'
      - '443:8443'
    links:
      - zabbix-pgsql
      - zabbix-server
    depends_on:
      - zabbix-pgsql
      - zabbix-server
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
      - /var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - /var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
  grafana-server:
    image: grafana/grafana:latest
    container_name: zabbix-grafana
    ports:
      - "3000:3000"
    volumes:
      - /etc/ssl/grafana:/etc/ssl/grafana:ro
      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    links:
        - zabbix-pgsql
